package com.enterprise.customerservice.domain.usecases

import com.enterprise.customerservice.data.models.KnowledgeDocument
import com.enterprise.customerservice.data.repository.CustomerServiceRepository

/**
 * Use case for ingesting knowledge base documents
 */
class IngestKnowledgeUseCase(
    private val repository: CustomerServiceRepository
) {
    
    suspend operator fun invoke(
        documentId: String,
        title: String,
        content: String,
        category: String,
        metadata: String = "{}"
    ): Result<Unit> {
        return try {
            // Validate input
            if (documentId.isBlank() || title.isBlank() || content.isBlank()) {
                return Result.failure(IllegalArgumentException("Document fields cannot be empty"))
            }
            
            // Create document
            val document = KnowledgeDocument(
                documentId = documentId,
                title = title,
                content = content,
                category = category,
                embedding = "", // Will be generated by repository
                metadata = metadata
            )
            
            // Ingest document
            repository.ingestKnowledgeDocument(document)
            
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    
    suspend fun ingestBatch(documents: List<KnowledgeDocument>): Result<Unit> {
        return try {
            repository.ingestKnowledgeDocuments(documents)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
